### ISSUE TITLE
Loading stylesheet from local file

### ISSUE THREAD

**Issue by clem9669** [Haxxnet/nmap-bootstrap-xsl#1]
Hi @l4rm4nd,

Is there a way to load the stylesheet from a local file e.g. after a git clone ?

Cheers

**Comment by l4rm4nd** [comment]
From the [README.md](https://github.com/Haxxnet/nmap-bootstrap-xsl/blob/main/README.md):

````
sudo apt install xsltproc
xsltproc -o report.html nmap-bootstrap.xsl <your-nmap.xml>
````

**Comment by clem9669** [comment]
From nmap man [page](https://linux.die.net/man/1/nmap):

> --stylesheet path or URL (Set XSL stylesheet to transform XML output) .
    Nmap ships with an XSL. stylesheet. named nmap.xsl. for viewing or translating XML output to HTML.. The XML output includes an xml-stylesheet directive which points to nmap.xml where it was initially installed by Nmap. Run the XML file through an XSLT processor such as xsltproc [17] . to produce an HTML file. Directly opening the XML file in a browser no longer works well because modern browsers limit the locations a stylesheet may be loaded from. If you wish to use a different stylesheet, specify it as the argument to --stylesheet. You must pass the full pathname or URL. One common invocation is --stylesheet http://nmap.org/svn/docs/nmap.xsl. This tells an XSLT processor to load the latest version of the stylesheet from Nmap.Org. The --webxml option does the same thing with less typing and memorization. Loading the XSL from Nmap.Org makes it easier to view results on a machine that doesn't have Nmap (and thus nmap.xsl) installed. So the URL is often more useful, but the local filesystem location of nmap.xsl is used by default for privacy reasons. 


Have you managed to load directly into nmap the XLS sheet other than converting ?

**Comment by l4rm4nd** [comment]
> From nmap man [page](https://linux.die.net/man/1/nmap):
> 
> > --stylesheet path or URL (Set XSL stylesheet to transform XML output) .
> > Nmap ships with an XSL. stylesheet. named nmap.xsl. for viewing or translating XML output to HTML.. The XML output includes an xml-stylesheet directive which points to nmap.xml where it was initially installed by Nmap. Run the XML file through an XSLT processor such as xsltproc [17] . to produce an HTML file. Directly opening the XML file in a browser no longer works well because modern browsers limit the locations a stylesheet may be loaded from. If you wish to use a different stylesheet, specify it as the argument to --stylesheet. You must pass the full pathname or URL. One common invocation is --stylesheet http://nmap.org/svn/docs/nmap.xsl. This tells an XSLT processor to load the latest version of the stylesheet from Nmap.Org. The --webxml option does the same thing with less typing and memorization. Loading the XSL from Nmap.Org makes it easier to view results on a machine that doesn't have Nmap (and thus nmap.xsl) installed. So the URL is often more useful, but the local filesystem location of nmap.xsl is used by default for privacy reasons.
> 
> Have you managed to load directly into nmap the XLS sheet other than converting ?

From the [README.md](https://github.com/Haxxnet/nmap-bootstrap-xsl/blob/main/README.md):

You can define the stylesheet directly when running nmap:

````
nmap -sS -Pn --stylesheet https://raw.githubusercontent.com/Haxxnet/nmap-bootstrap-xsl/main/nmap-bootstrap.xsl scanme.nmap.org
````

You should be able to define a local file too instead of a URL link. The XML file will then be properly formatted according to the stylesheet. You can open the XML directly in a supported browser. However, you'll not receive a .html report this way. Obtaining a single HTML report file requires converting via the `xsltproc` binary.

Another option would be to directly paste the stylesheet definition into the nmap.xml file after your nmap scan was finished. Insert the following after `<!DOCTYPE nmaprun>` inside the XML file:

````
<?xml-stylesheet href="https://raw.githubusercontent.com/Haxxnet/nmap-bootstrap-xsl/main/nmap-bootstrap.xsl" type="text/xsl"?>
````
Again, you can define a local file too but the HTML report only works locally with the .XSL file then.
