### ISSUE TITLE
Fix host address sorting (put .2 above .11)

### ISSUE THREAD

**Issue by jvedman** [Haxxnet/nmap-bootstrap-xsl#2]
First, this is an awesome project, so many <3s. That said, there is an issue with host IP sorting. I am happy to do some of the lifting here, but definitely need to make Host - Address sorts go in proper order (.x.2 should be above .x.11, .2.x should be above .11.x, etc.). I'll start poking, but if you can give me a pointer of where to look that would be awesome.

**Comment by l4rm4nd** [comment]
Hey @jvedman ,

so sorry for the late response. I've overseen your issue totally.

I will have a look at the sorting too. Basically, those tables are Bootstrap datatables, which are initialized by JavaScript.

The IPs are considered strings, therefore sorting does not properly work. We have to create a custom sorting algorithm in JS and use it to initialize the datatables.

The relevant JS is located at the end of the `nmap-boostrap.xsl` file if you want to have a look at it too.

**Comment by l4rm4nd** [comment]
I've added https://datatables.net/plug-ins/sorting/ip-address, which solves the IP address sorting problem.

Cheers!
